--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pixelwhiz/ParachutePlus
build-by-default: true
branches:
- master
projects:
  ParachutePlus:
    path: ""
    lint: false
    icon: "icon.png"
...
