---
name: ParachutePlus
version: 1.1.1
main: pixelwhiz\parachuteplus\Main
api: 5.0.0
author: pixelwhiz
website: https://github.com/pixelwhiz/ParachutePlus
src-namespace-prefix: pixelwhiz\parachuteplus
permissions:
  parachuteplus.cmd:
    description: 'Allows players to use this command'
    default: op
...
